/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#004145",
        "tertiary-fixed-dim": "#d57fff",
        "on-primary": "#005f64",
        "surface-tint": "#99f7ff",
        "secondary": "#8097ff",
        "surface": "#0c0e12",
        "on-surface-variant": "#aaabb0",
        "surface-dim": "#0c0e12",
        "on-tertiary-container": "#000000",
        "secondary-dim": "#3c66ff",
        "surface-container-high": "#1d2025",
        "surface-container": "#171a1f",
        "primary-container": "#00f1fe",
        "surface-variant": "#23262c",
        "on-surface": "#f6f6fc",
        "error-dim": "#d7383b",
        "on-error-container": "#ffa8a3",
        "surface-container-highest": "#23262c",
        "error": "#ff716c",
        "tertiary": "#d277ff",
        "primary-dim": "#00e2ee",
        "tertiary-dim": "#d277ff",
        "primary-fixed-dim": "#00e2ee",
        "on-tertiary-fixed": "#2b0041",
        "secondary-container": "#0f4aef",
        "primary-fixed": "#00f1fe",
        "outline-variant": "#46484d",
        "inverse-primary": "#006a70",
        "error-container": "#9f0519",
        "on-secondary-container": "#f8f7ff",
        "outline": "#74757a",
        "surface-bright": "#292c33",
        "tertiary-container": "#bf5af2",
        "on-secondary-fixed": "#00278f",
        "on-secondary": "#00175f",
        "on-secondary-fixed-variant": "#003ed3",
        "on-tertiary-fixed-variant": "#5e0087",
        "on-background": "#f6f6fc",
        "secondary-fixed-dim": "#b4c1ff",
        "inverse-on-surface": "#53555a",
        "tertiary-fixed": "#dd94ff",
        "on-tertiary": "#380052",
        "secondary-fixed": "#c7cfff",
        "on-error": "#490006",
        "on-primary-fixed-variant": "#006065",
        "surface-container-lowest": "#000000",
        "on-primary-container": "#00555a",
        "primary": "#99f7ff",
        "surface-container-low": "#111318",
        "inverse-surface": "#f9f9ff",
        "background": "#0c0e12"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"],
        "mono": ["IBM Plex Mono", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
