"""add_persistence_tables

Adds two additive-only tables:
  - rate_limit_records: DB-backed sliding-window rate limiter buckets
  - token_blacklist:    JWT revocation store for logout / forced expiry

Both tables are new (no existing data modified). Safe to run on live DB.

Revision ID: babad7811a25
Revises: 0001
Create Date: 2026-04-24 15:06:30.322338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'babad7811a25'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hits', sa.Integer(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_records_id'), 'rate_limit_records', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_key'), 'rate_limit_records', ['key'], unique=False)
    op.create_index(op.f('ix_rate_limit_records_timestamp'), 'rate_limit_records', ['timestamp'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_rate_limit_records_timestamp'), table_name='rate_limit_records')
    op.drop_index(op.f('ix_rate_limit_records_key'), table_name='rate_limit_records')
    op.drop_index(op.f('ix_rate_limit_records_id'), table_name='rate_limit_records')
    op.drop_table('rate_limit_records')
    # ### end Alembic commands ###
